apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: nexus3-gcs
    # following the available images and tags on my temporary GCP account
    newName: us-east1-docker.pkg.dev/qwiklabs-gcp-01-e7b12b7bf42a/nexus-repo/nexus3-gcs
    newTag: "3.61.0"

patches:
  - target:
      kind: PersistentVolumeClaim
      name: nexus-data-pvc
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: standard-rwo
  - target:
      kind: Deployment
      name: nexus
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "1000Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "150m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "1400Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "800m"
