apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data-pvc
  labels:
    app: nexus
spec:
  # deploying locally using k3s, points to local-path (FOR k3s, patched using kustomize overlays)
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
